name: Auto Zip and Release

on:
  push:
    branches:
      - master

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: process
        id: process
        run: |
          VERSION=`cat module.prop | grep -oP "(?<=version=).*" | cut -d "=" -f2`
          FULL_TAG="$VERSION"
          echo "tag=$FULL_TAG" >> $GITHUB_OUTPUT
          zip -r magisk-wifiadb-neta.zip ./*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "magisk-wifiadb-neta.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.process.outputs.tag }}
          prerelease: true
